[package]
name = "gravity"
version = "0.1.0"
edition = "2021"

[dependencies]
compute = { git = "https://github.com/connorslade/compute", features = [
    "interactive",
] }

anyhow = "1.0.95"
encase = { version = "0.10.0", features = ["nalgebra"] }
image = "0.25.5"
rand = "0.8.5"
