[package]
name = "e_field"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.1"
rayon = "1.10.0"
svg = "0.18.0"

# Interactive mode
once_cell = "1.20.2"
pollster = "0.3.0"
vello = "0.3.0"
wgpu = "22.1.0"
winit = "0.30.5"