[package]
name = "e_field"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.1"
svg = "0.18.0"

# Interactive mode
pollster = "0.3.0"
vello = "0.3.0"
wgpu = "22.1.0"
winit = "0.30.5"
